title: Gabriela Slaninková
description: Diplomová práca
favicon: /assets/img/avatar.PNG
baseurl: https://gabikaslani.github.io/diploma-thesis/
url: https://gabikaslani.github.io/diploma-thesis/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Bc. Gabriela Slaninková
  title: DIPLOMOVÁ PRÁCA
  subtitle: Mobilná aplikácia na nájdenie optimálnej trasy v MHD z reálnych dát
  email: gabika.slani@gmail.com
  github: gabikaSlani
  gavatar: /resumecard/assets/img/avatar.PNG
  stackoverflow:
#  stackoverflow: 4582127
  programmingSkills:
    - skill1:
      name: Webová stránka
      percentage: 100%
    - skill2:
      name: Prototyp
      percentage: 90%
    - skill3:
      name: Latex šablóna
      percentage: 70%
    - skill4:
      name: Prezentácia
      percentage: 70%
    - skill5:
      name: Štúdium článkov
      percentage: 90%
