title: Dong Liang's CV
description: ddbullfrog's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Bc. Gabriela Slaninková
  title: DIPLOMOVÁ PRÁCA
  subtitle: Mobilná aplikácia na nájdenie optimálnej trasy v MHD z reálnych dát
  email: gabika.slani@gmail.co
  github: gabikaSlani
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  zadanie:
    - work1:
      title: Anotácia
      description: Existuje aplikácia imhd ba, ktorá slúži na plánovanie cesty v MHD v Bratislave na základe statických cestovných poriadkov. Cieľom tejto práce je nájsť spôsob určovania optimálnej cesty a naprogramovať aplikáciu, ktorá to dokáže urobiť s reálnych dát o pohybe vozidiel MHD.
      started: 0
    - work1:
      title: Ciele
      description: ...
      started: 0

  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Webová stránka
      percentage: 100%
    - skill2:
      name: Prototyp
      percentage: 90%
    - skill3:
      name: Latex šablóna
      percentage: 70%
    - skill4:
      name: Prezentácia
      percentage: 70%
    - skill5:
      name: Štúdium článkov
      percentage: 90%
