title: Gabriela Slaninková
description: Diplomová práca
favicon: /assets/img/avatar.PNG
baseurl: https://gabikaslani.github.io/diploma-thesis/
url: https://gabikaslani.github.io/diploma-thesis/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Bc. Gabriela Slaninková
  title: DIPLOMOVÁ PRÁCA
  subtitle: Mobilná aplikácia na nájdenie optimálnej trasy v MHD z reálnych dát
  email: gabika.slani@gmail.com
  github: gabikaSlani
  gavatar: /resumecard/assets/img/avatar.PNG
  stackoverflow:
#  stackoverflow: 4582127
  programmingSkills:
    - skill1:
      name: Latex šablóna
      percentage: 100%
    - skill2:
      name: Štúdium článkov
      percentage: 100%
    - skill3:
      name: Prototyp A* algoritmus
      percentage: 100%
    - skill4:
      name: Prezentácia 1
      percentage: 100%
    - skill5:
      name: Kapitola 1 - Východiská
      percentage: 100%
    - skill6:
      name: Štúdium RAPTOR algoritmus
      percentage: 100%
    - skill7:
      name: Kapitola 2 - Návrh
      percentage: 60%
    - skill8:
      name: Návrh architektúry systému
      percentage: 100%
    - skill9:
      name: Vystaveie webservisov
      percentage: 100%
    - skill10:
      name: Vytvorenie testovacích dát
      percentage: 100%
    - skill11:
      name: Návrh obrazoviek aplikácie
      percentage: 100%
    - skill12:
      name: Implementácia frontendovej časti
      percentage: 80%
    - skill13:
      name: Návrh a implementácia dátovej štruktúry
      percentage: 100%
    - skill14:
      name: Implemenácia základnej verzie RAPTOR
      percentage: 100%
    - skill15:
      name: Prezentácia 2
      percentage: 100%
    - skill16:
      name: Parsovanie statických dát od DPB
      percentage: 10%
    - skill17:
      name: Implementácia vylepšenej verzie RAPTOR (k-optimálnych ciest)
      percentage: 0%
    - skill18:
      name: Rozšírenie o rRAPTOR
      percentage: 0%
    - skill19:
      name: Parsovanie meškaní zo súboru
      percentage: 0%
    - skill20:
      name: Zohľadniť meškanie spojov pri vyhľadávaní
      percentage: 0%
